title: "Global Precipitation Climatology Project"
description: >
  Global Precipitation Climatology Project (GPCP) Daily Version 1.3 gridded, merged ty
  satellite/gauge precipitation Climate data Record (CDR) from 1996 to 2025-05-19.
provenance:
  providers:
    - name: "NOAA NCEI"
      description: "National Oceanographic & Atmospheric Administration National Centers for Environmental Information"
      roles:
        - host
        - licensor
      url: https://www.ncei.noaa.gov/products/global-precipitation-climatology-project
    - name: "University of Maryland"
      description: >
        University of Maryland College Park Earth System Science Interdisciplinary Center
        (ESSIC) and Cooperative Institute for Climate and Satellites (CICS).
      roles:
        - producer
      url: http://gpcp.umd.edu/
  license: "No constraints on data access or use."
maintainers:
  - name: "Ryan Abernathey"
    orcid: "0000-0001-5999-4917"
    github: rabernat
  - name: "Raphael Hagen"
  - github: norlandrhagen 
  
